server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location = /app-admin {
        return 308 /app-admin/;
    }

    location /app-admin/ {
        try_files $uri $uri/ /app-admin/index.html;
    }
}
