import React,{useState} from 'react';
import {QuestionEditor} from './ContentEditors.jsx';
const api=import.meta.env.VITE_API_URL||'/api';
export default function Games({token,games,onSaved}){
 const [form,setForm]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const open=g=>{setError('');setForm(g?{...g,items:g.items.join('\n')}:{title:'',description:'',type:'memory',active:true,items:'',questionItems:[]});};
 const save=async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`${api}/games${form.id?'/'+form.id:''}`,{method:form.id?'PATCH':'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({...form,items:form.items.split('\n').map(x=>x.trim()).filter(Boolean)})});const d=await r.json();if(!r.ok)throw Error(d.error);await onSaved();setForm(null);}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <><div className="editor-heading"><h2>Мини тоглоом</h2><button onClick={()=>open(null)}>+ Тоглоом нэмэх</button></div><p>Ой тогтоолт, дараалал, богино асуултын тоглоом. Coin болон XP олгохгүй.</p>{form&&<form className="panel" onSubmit={save}><fieldset disabled={busy}><label>Нэр<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Тайлбар<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Төрөл<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="memory">Хосоо олох</option><option value="sequence">Дараалал эвлүүлэх</option><option value="quiz">Богино сорил</option></select></label><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Апп дээр харуулах</label>{form.type==='quiz'?<QuestionEditor items={form.questionItems} onChange={questionItems=>setForm({...form,questionItems})}/>:<label>{form.type==='sequence'?'Зөв дарааллаар, мөр бүрт нэг алхам':'Мөр бүрт нэг хосын нэр (2–8)'}<textarea required rows={8} value={form.items} onChange={e=>setForm({...form,items:e.target.value})}/></label>}{error&&<p className="error">{error}</p>}<button>{busy?'Хадгалж байна…':'Хадгалах'}</button><button type="button" className="secondary" onClick={()=>setForm(null)}>Болих</button></fieldset></form>}{games.map(g=><article className="panel" key={g.id}><h3>{g.title}</h3><p>{g.type} • {g.active?'Идэвхтэй':'Нуусан'}</p><button onClick={()=>open(g)}>Засах</button></article>)}</>;
}
