import React,{useState} from 'react';
const pct=v=>v==null?'—':`${v}%`;
function Table({heads,rows}){return <div className="table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={heads.length}>Өгөгдөл хараахан алга.</td></tr>}</tbody></table></div>}
const Metric=({label,children})=><article className="metric"><strong>{children}</strong><span>{label}</span></article>;
export default function LearningAnalytics({data}){
 const [view,setView]=useState('teacher');if(!data.funnel)return <p role="status">Сургалтын өгөгдөл уншиж байна…</p>;
 const completed=data.courses.reduce((n,c)=>n+c.completed,0),started=data.courses.reduce((n,c)=>n+c.started,0);
 return <><section className="panel"><p className="eyebrow">СУРАЛЦАХ → ШАЛГАХ → ДАВТАХ</p><h2>Сургалтын чанар</h2><p>Сүүлийн 30 хоногийн үйлдэл. Курсийн ахиц, pre/post хэмжилт нийт хугацаагаар.</p><p className="hint">Бүртгэл эхэлсэн: {data.startedAt?new Date(data.startedAt).toLocaleString():'Шинэ үйлдэл хүлээж байна'}. Хуучин бүртгээгүй үйлдлийг нөхөж тооцоогүй.</p><div className="analytics-tabs">{[['teacher','Эмч-багш'],['developer','Хөгжүүлэгч'],['leadership','Удирдлага']].map(([id,label])=><button key={id} className={view===id?'':'secondary'} aria-pressed={view===id} onClick={()=>setView(id)}>{label}</button>)}</div><small>Зөвхөн админд нээлттэй харагдацууд. Тусдаа багш / хөгжүүлэгчийн эрх дараагийн шатанд нэмэгдэнэ.</small></section>
 <section className="metrics"><Metric label="Идэвхтэй суралцагч · 30 хоног">{data.active}</Metric><Metric label="Курс дуусгалт · нийт">{started?pct(Math.round(100*completed/started)):'—'}</Metric><Metric label="Эхний хариултын зөв хувь">{pct(data.accuracy)}</Metric><Metric label="Тест эхлүүлсэн оролдлого">{data.funnel.started}</Metric></section>
 <section className="panel"><h2>Анхаарах зүйлс</h2>{data.insights.length?<ul>{data.insights.map((t,i)=><li key={i}>{t}</li>)}</ul>:<p>Асуулт бүрт 5-аас доошгүй суралцагчийн өгөгдөл цугласны дараа автомат insight гарна.</p>}</section>
 {view==='teacher'&&<><section className="panel"><h2>Сэдвийн үр дүн</h2><Table heads={['Сэдэв','Эхний хариулт','Зөв хувь']} rows={data.topics.map(t=>[t.topic,t.n,pct(t.accuracy)])}/></section><section className="panel"><h2>Асуултын чанар</h2><p>Асуултын хувилбар тус бүрээр, суралцагчийн эхний хариултыг тооцно. n бага үед дүгнэлт хийхгүй.</p><Table heads={['Асуулт / сэдэв','n','Зөв %','Дундаж секунд','Сонголтын тархалт']} rows={data.questions.map(q=>[<>{q.prompt}<small style={{display:'block'}}>{q.topic} · {q.scope}</small></>,q.n,pct(q.accuracy),q.seconds??'—',q.choices.map((n,i)=>`${String.fromCharCode(65+i)}: ${n}${i===q.correctAnswer?' ✓':''}`).join(' / ')])}/><p className="hint">Хугацааг шинэ тест клиентээс бүртгэнэ. 30 минутаас урт хэмжилтийг хасна. Discrimination тооцоолол хараахан ороогүй.</p></section></>}
 {view==='developer'&&<><section className="metrics"><Metric label="Эхэлсэн оролдлого">{data.funnel.started}</Metric><Metric label="Тэдгээрээс дууссан">{data.funnel.completed}</Metric><Metric label="24+ цаг дуусаагүй">{data.funnel.pending}</Metric><Metric label="Үр дүнгүй хайлт">{data.emptySearches} / {data.searches}</Metric></section><section className="panel"><h2>Хэсгийн хэрэглээ</h2><Table heads={['Хэсэг / товч','Тоо']} rows={data.features.map(f=>[f.name,f.count])}/><p className="hint">Зөвхөн нэвтэрсэн хэрэглэгчийг бүртгэнэ. Хайлтын үг, өвчтөний текст хадгалахгүй. 24 цаг дуусаагүй нь drop-off байж болох дохио; баталгаатай гарсан гэсэн үг биш. Crash rate хараахан хэмжигдээгүй.</p></section></>}
 {view==='leadership'&&<section className="panel"><h2>Идэвх ба эргэн ирэлт</h2><p>Өмнөх 30 хоног: {data.previousActive}. Одоогийн 30 хоног: {data.active}.</p><p>Өмнөх үеийн хэрэглэгчдийн эргэн ирэлт: {pct(data.returnRate)}</p><small>Хоёр 30 хоногийн цонхоор тооцно; D1/D7 retention биш.</small></section>}
 <section className="panel"><h2>Курсийн үр дүн</h2><Table heads={['Курс','Ахицтай','Дууссан','Completion','Pre/post хос n','Өөрчлөлт · пункт']} rows={data.courses.map(c=>[c.title,c.started,c.completed,pct(c.completion),c.paired,c.improvement==null?'—':`${c.improvement>0?'+':''}${c.improvement}`])}/><p className="hint">Pre-test ба эхний post-test, одоогийн асуултын хувилбараар хослуулна. Хүндрэл, суралцах зорилтыг багш ижилсүүлнэ. Энэ өөрчлөлт нь сургалтын шалтгаант нөлөөний баталгаа биш.</p>{view!=='leadership'&&data.courses.map(c=><details key={c.id}><summary>{c.title} · хичээлээр</summary><Table heads={['Хичээл','Дууссан']} rows={c.lessons.map(l=>[l.title,l.completed])}/></details>)}</section></>;
}
