import React,{useState} from 'react';
const api=async(path,token,body,method='PATCH')=>{const r=await fetch(`${import.meta.env.VITE_API_URL||'/api'}${path}`,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);return d;};
function Field({label,value,onChange,type='text',...props}){return <label>{label}<input type={type} value={value??''} onChange={e=>onChange(type==='number'?Number(e.target.value):e.target.value)} {...props}/></label>}
function Choice({label,value,onChange,options}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x} value={x}>{x}</option>)}</select></label>}
function Toggle({label,value,onChange}){return <label className="check"><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/>{label}</label>}
function useSave(token,onSaved){const [error,setError]=useState(''),[busy,setBusy]=useState(false),[success,setSuccess]=useState('');const save=async(path,body,method,done)=>{setBusy(true);setError('');setSuccess('');try{await api(path,token,body,method);await onSaved();done?.();setSuccess('Хадгаллаа.');}catch(e){setError(e.message);}finally{setBusy(false);}};return {save,busy,notice:<>{error&&<p role="alert" className="error">{error}</p>}{success&&<p role="status" className="success">{success}</p>}</>};}
const emptyUser={name:'',email:'',password:'',role:'learner',profession:'Ерөнхий',memberLevel:'bronze',paymentStatus:'unpaid',active:true};
export function Users({token,users,onSaved}){const [form,setForm]=useState(null);const {save,busy,notice}=useSave(token,onSaved);const field=k=>v=>setForm({...form,[k]:v});return <>{notice}<section className="panel"><div className="section-heading"><div><h2>Хэрэглэгчид</h2><p>Апп руу эдгээр и-мэйл, нууц үгээр нэвтэрнэ.</p></div><button onClick={()=>setForm({...emptyUser})}>+ Хэрэглэгч нэмэх</button></div>{form&&<form className="editor form-grid" onSubmit={e=>{e.preventDefault();save(`/users${form.id?'/'+form.id:''}`,form,form.id?'PATCH':'POST',()=>setForm(null));}}><h3>{form.id?'Хэрэглэгч засах':'Шинэ хэрэглэгч'}</h3><Field required label="Нэр" value={form.name} onChange={field('name')}/><Field required label="И-мэйл" type="email" value={form.email} onChange={field('email')}/><Field label={form.id?'Шинэ нууц үг (хоосон бол хэвээр)':'Нууц үг (8–72 тэмдэгт)'} type="password" required={!form.id} minLength={8} maxLength={72} value={form.password} onChange={field('password')}/><Choice label="Мэргэжил" value={form.profession} onChange={field('profession')} options={['Ерөнхий','Дотор өвчин','Хүүхэд','Мэс засал','Яаралтай тусламж','Дүрс оношилгоо','Шүд','Бусад']}/><Choice label="Эрх" value={form.role} onChange={field('role')} options={['learner','admin']}/><Choice label="Гишүүнчлэл" value={form.memberLevel} onChange={field('memberLevel')} options={['bronze','silver','gold','premium']}/><Choice label="Төлбөр" value={form.paymentStatus} onChange={field('paymentStatus')} options={['unpaid','trial','paid']}/><Toggle label="Идэвхтэй" value={form.active} onChange={field('active')}/><div><button disabled={busy}>Хадгалах</button> <button type="button" className="secondary" onClick={()=>setForm(null)}>Болих</button></div></form>}<div className="table-wrap"><table><thead><tr>{['Нэр','И-мэйл','Эрх / гишүүнчлэл','Төлөв',''].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.role} / {u.memberLevel}</td><td>{u.active?'Идэвхтэй':'Идэвхгүй'}</td><td><button onClick={()=>setForm({...emptyUser,...u,password:''})}>Засах</button></td></tr>)}</tbody></table></div></section></>}
const emptyStory={label:'Мэдээ',title:'',body:'',imageUrl:'',published:true,order:0,expiresAt:''};
const mediaUrl=url=>url?.startsWith('/uploads/')&&import.meta.env.VITE_API_URL?.startsWith('http')?new URL(url,import.meta.env.VITE_API_URL).href:url;
export function Stories({token,stories,onSaved}){
 const [form,setForm]=useState(null),[uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState('');
 const {save,busy,notice}=useSave(token,onSaved);const field=k=>v=>setForm(current=>({...current,[k]:v}));
 async function upload(file){
  if(!file)return;
  if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){setUploadError('JPG, PNG, WebP зураг • 8 MB хүртэл.');return;}
  setUploading(true);setUploadError('');
  try{const body=new FormData();body.append('image',file);const r=await fetch(`${import.meta.env.VITE_API_URL||'/api'}/uploads/image`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body});const d=await r.json();if(!r.ok)throw Error(d.error);field('imageUrl')(d.url);}catch(e){setUploadError(e.message);}finally{setUploading(false);}
 }
 const edit=s=>{setUploadError('');setForm({...s,expiresAt:s.expiresAt?new Date(new Date(s.expiresAt).getTime()-new Date(s.expiresAt).getTimezoneOffset()*60000).toISOString().slice(0,16):''});};
 return <>{notice}<section className="panel"><div className="section-heading"><div><h2>Мэдээ • Stories</h2><p>Нийтэлсэн мэдээ аппын нүүрэнд автоматаар шинэчлэгдэнэ. Ноорог болон хугацаа дууссан мэдээ харагдахгүй.</p></div><button disabled={uploading||busy} onClick={()=>edit({...emptyStory})}>+ Story нэмэх</button></div>
 {form&&<form className="editor form-grid" onSubmit={e=>{e.preventDefault();save(`/stories${form.id?'/'+form.id:''}`,{...form,expiresAt:form.expiresAt?new Date(form.expiresAt).toISOString():null},form.id?'PATCH':'POST',()=>setForm(null));}}>
 <Field required maxLength={32} label="Дугуйн доорх нэр" value={form.label} onChange={field('label')}/><Field required label="Гарчиг" value={form.title} onChange={field('title')}/>
 <label className="full">Мэдээний агуулга<textarea required value={form.body} onChange={e=>field('body')(e.target.value)}/></label>
 <label>Зураг байршуулах<input type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading||busy} onChange={e=>upload(e.target.files[0])}/><small>JPG / PNG / WebP • 8 MB хүртэл</small></label>
 <Field label="Зургийн холбоос (эсвэл файл байршуулна)" value={form.imageUrl} onChange={field('imageUrl')}/>
 {uploading&&<p role="status">Зураг байршуулж байна…</p>}{uploadError&&<p role="alert" className="error">{uploadError}</p>}
 <Field type="number" min={0} label="Дараалал" value={form.order} onChange={field('order')}/><Field type="datetime-local" label="Дуусах хугацаа (заавал биш)" value={form.expiresAt} onChange={field('expiresAt')}/>
 <Toggle label="Нийтлэх — хэрэглэгчид харуулах" value={form.published} onChange={field('published')}/>
 {form.imageUrl&&<img className="story-preview" src={mediaUrl(form.imageUrl)} alt="Story preview"/>}
 <div><button disabled={busy||uploading}>{form.published?'Хадгалж нийтлэх':'Ноорог хадгалах'}</button> <button type="button" disabled={uploading||busy} className="secondary" onClick={()=>setForm(null)}>Болих</button></div></form>}
 <div className="manager-grid">{stories.map(s=><article className="manager-card" key={s.id}>{s.imageUrl&&<img src={mediaUrl(s.imageUrl)} alt=""/>}<span className="eyebrow">{!s.published?'НООРОГ':s.expiresAt&&Date.parse(s.expiresAt)<Date.now()?'ДУУССАН':'НИЙТЛЭГДСЭН'}</span><h3>{s.title}</h3><p>{s.body}</p><div className="actions"><button disabled={uploading||busy} onClick={()=>edit(s)}>Засах</button>{(!s.published||s.expiresAt&&Date.parse(s.expiresAt)<Date.now())&&<button disabled={busy||uploading} onClick={()=>save(`/stories/${s.id}`,{published:true,expiresAt:null},'PATCH')}>Одоо нийтлэх</button>}</div></article>)}</div>{!stories.length&&<p>Мэдээ хараахан нэмээгүй байна.</p>}</section></>;
}
export function Coins({token,data,onSaved}){const {save,busy,notice}=useSave(token,onSaved);const [bonus,setBonus]=useState(null),[form,setForm]=useState({userId:'',amount:10,reason:'',requestId:crypto.randomUUID()});const users=data.users||[];return <>{notice}<section className="panel"><h2>Өдөр тутмын бонус</h2><p>Хэрэглэгч Улаанбаатарын цагаар өдөрт нэг удаа авна. Курсийн урамшууллыг “Курс ба видео” хэсгээс тохируулна.</p><form className="form-grid" onSubmit={e=>{e.preventDefault();save('/coins/settings',{dailyBonus:bonus??data.settings?.dailyBonus??10});}}><Field label="Өдрийн Premium coin" type="number" min={0} max={100000} value={bonus??data.settings?.dailyBonus??10} onChange={setBonus}/><button disabled={busy}>Бонус хадгалах</button></form></section><section className="panel"><h2>Coin нэмэх / хасах</h2><form className="form-grid" onSubmit={e=>{e.preventDefault();save('/coins/adjust',form,'POST',()=>setForm({...form,reason:'',requestId:crypto.randomUUID()}));}}><label>Хэрэглэгч<select required value={form.userId} onChange={e=>setForm({...form,userId:e.target.value})}><option value="">Сонгох</option>{users.map(u=><option key={u.id} value={u.id}>{u.name} ({u.balance} coin) — {u.email}</option>)}</select></label><Field required label="Дүн (хасах бол сөрөг тоо)" type="number" value={form.amount} onChange={amount=>setForm({...form,amount})}/><Field required label="Шалтгаан" value={form.reason} onChange={reason=>setForm({...form,reason})}/><button disabled={busy}>Coin өөрчлөх</button></form></section><section className="panel"><h2>Гүйлгээний түүх</h2><div className="table-wrap"><table><thead><tr><th>Хэрэглэгч</th><th>Дүн</th><th>Шалтгаан</th><th>Огноо</th></tr></thead><tbody>{(data.ledger||[]).map(x=><tr key={x.id}><td>{users.find(u=>u.id===x.userId)?.name||x.userId}</td><td>{x.amount>0?'+':''}{x.amount}</td><td>{x.reason}</td><td>{new Date(x.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div></section></>}
export function Discussions({token,discussions,onSaved}){const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[selected,setSelected]=useState(null),[reply,setReply]=useState('');const {save,busy,notice}=useSave(token,onSaved);const p=discussions.find(x=>x.id===selected);return <>{notice}<section className="panel"><h2>Кейс хэлэлцүүлгийн удирдлага</h2><div className="form-grid"><Field label="Гарчиг, сэдэв, агуулгаар хайх" value={query} onChange={setQuery}/><Choice label="Төлөв" value={status} onChange={setStatus} options={['all','open','closed','hidden']}/></div><div className="manager-grid">{discussions.filter(x=>(`${x.title} ${x.body} ${x.specialty}`).toLowerCase().includes(query.toLowerCase())&&(status==='all'||status==='hidden'&&x.hidden||status==='closed'&&x.closed||status==='open'&&!x.closed&&!x.hidden)).map(x=><article className="manager-card" key={x.id}><span className="eyebrow">{x.specialty} • {x.hidden?'НУУГДСАН':x.closed?'ХААГДСАН':'НЭЭЛТТЭЙ'}</span><h3>{x.title}</h3><p>{x.author||'Нэргүй эмч'} • {x.replies.length} хариулт</p><button onClick={()=>{setSelected(x.id);setReply('');}}>Хэлэлцүүлэг удирдах</button></article>)}</div>{!discussions.length&&<p>Апп дээр эмч нарын нэмсэн кейсүүд энд харагдана.</p>}</section>{p&&<section className="panel"><h2>{p.title}</h2><p className="preserve-lines">{p.body}</p><div className="actions"><button disabled={busy} onClick={()=>save(`/discussions/${p.id}`,{closed:!p.closed})}>{p.closed?'Дахин нээх':'Кейс хаах'}</button><button disabled={busy} onClick={()=>save(`/discussions/${p.id}`,{hidden:!p.hidden})}>{p.hidden?'Хэрэглэгчид харуулах':'Хэрэглэгчээс нуух'}</button><button className="secondary" onClick={()=>setSelected(null)}>Болих</button></div>{p.replies.map((r,i)=><blockquote key={i}>{r}</blockquote>)}{!p.closed&&<form onSubmit={e=>{e.preventDefault();save(`/discussions/${p.id}`,{reply},'PATCH',()=>setReply(''));}}><label>Админы хариулт<textarea required value={reply} onChange={e=>setReply(e.target.value)}/></label><button disabled={busy}>Хариулт нэмэх</button></form>}</section>}</>}
